## script for analysis of mcc_timecourse integrated dataset

library(Seurat)
library(dplyr)
library(ggplot2)
library(reshape2)
library(gridExtra)

#################### LOAD IN SEURAT OBJECT ###########################
#seur = readRDS("v3/mcc_timecourse_v3.rds") ## generated by seurat.integration.R script
seur = readRDS("v3/mcc_timecourse_v3_13dim.rds") ##updated object, generated below
seur$orig.ident <- factor(seur$orig.ident, levels=c("Ad1_agg_soupx","Ad3","Ad9_soupx","Ad36_soupx"))


#################### PCs TO USE IN ANALYSIS #########################
DefaultAssay(seur)<- "integrated"

pdf("v3/mcc_timecourse_v3_elbowplot.pdf")
ElbowPlot(seur, ndims = 40)
dev.off()

for(x in 16:20){
        seur <- RunUMAP(seur, reduction="pca",dims=1:x)
        
        seur = FindNeighbors(seur, dims=1:x)
        seur = FindClusters(seur, resolution = 0.3)
        png(paste0("v3/mcc_timecourse_v3_",x,"pcs_clusters.png"),width=561,height=362)
        print(DimPlot(seur,label=T))
        dev.off()
}

### go with 13 PCs, since good between on elbow plot
seur <- RunUMAP(seur, reduction="pca",dims=1:13)
seur = FindNeighbors(seur, dims=1:13)
seur = FindClusters(seur, resolution = 0.2)


##################### UMAP PLOTS #########################################

pdf("v3/mcc_timecourse_v3_res0.3_cluster.pdf",useDingbats = F,height=8,width=11)
DimPlot(seur, group.by="integrated_snn_res.0.3",label=F,pt.size = 1.5,cols=colors) + theme_void() +theme(legend.position = "none") + ggtitle("")
dev.off()

mcc_color <- colorRampPalette(c("lightskyblue2", "royalblue4"))


colors=c("#009245","#F7A12D","darkgoldenrod","indianred",mcc_color(5)[5],"#996699","plum","#998675",mcc_color(5)[1],mcc_color(5)[3])


pdf("v3/mcc_timecourse_v3_res0.3_cluster_splitorig.pdf",useDingbats = F,height=8,width=11)
DimPlot(seur, group.by="integrated_snn_res.0.3",split.by="orig.ident",ncol = 2,pt.size = 1,cols = colors) + theme_void() + ggtitle("") + theme(legend.position = "none",strip.text = element_blank())
dev.off()


##################### CELL CYCLE #########################################
## try tricycle for assigning cell cycle scores
library(tricycle)

sc=as.SingleCellExperiment(seur,assay = "RNA")

sc=project_cycle_space(sc, species = "mouse",gname.type = "SYMBOL")
sc=estimate_cycle_position(sc)

## check that looks correct

data=as.data.frame(reducedDim(sc,type = "tricycleEmbedding"))
lab= colData(sc)$tricyclePosition

data$tricyclePosition <- lab

ggplot(data, aes(x=PC1, y=PC2,color=tricyclePosition))+
        geom_point()+
        scale_color_gradientn(colors=c("#2E22EA", "#9E3DFB", "#F86BE2", "#FCCE7B", "#C4E416", "#4BBA0F", "#447D87", "#2C24E9"))

top2a.idx <- which(rownames(sc) == 'Top2a')
fit.l <- fit_periodic_loess(sc$tricyclePosition,
                            assay(sc, 'logcounts')[top2a.idx,],
                            plot = TRUE,
                            x_lab = "Cell cycle position \u03b8", y_lab = "log2(Top2a)",
                            fig.title = paste0("Expression of Top2a along \u03b8 (n=",
                                               ncol(sc), ")"))
names(fit.l)
fit.l$fig + theme_bw(base_size = 14)

## alternative method - a lot of NAs in this approach, prefer the tricyclePosition values
sc <- estimate_Schwabe_stage(sc, gname.type = 'SYMBOL',
                                              species = 'mouse')
scater::plotReducedDim(sc, dimred = "tricycleEmbedding",
                       colour_by = "CCStage") +
        labs(x = "Projected PC1", y = "Projected PC2",
             title = paste0("Projected cell cycle space (n=", ncol(sc), ")")) +
        theme_bw(base_size = 14)

plot_ccposition_den(sc$tricyclePosition,
                    sc$CCStage, 'CCStage', fig.title = "Kernel density of \u03b8") +
        theme_bw(base_size = 14)

plot_ccposition_den(sc$tricyclePosition,
                    sc$CCStage, 'CCStage', type = "circular",
                    bw = 10,  fig.title = "Kernel density of \u03b8") +
        theme_bw(base_size = 14)

#### place values back into Seurat object
identical(colnames(seur),colnames(sc))
seur$tricyclePosition <- sc$tricyclePosition
seur$CCStage <- sc$CCStage

pdf("v3/circle_tricycle_scale.pdf",height=4,width=4)
circle_scale_legend(hue.colors = c("#2E22EA", "#9E3DFB", "#F86BE2", "#FCCE7B", "#C4E416", "#4BBA0F", "#447D87", "#2C24E9"))
dev.off()

pdf("v3/mcc_timecourse_v3_tricyclePosition.pdf",height=8,width=11,useDingbats = F)
FeaturePlot(seur, "tricyclePosition",pt.size=1.5,raster=T) +        
        scale_color_gradientn(colors=c("#2E22EA", "#9E3DFB", "#F86BE2", "#FCCE7B", "#C4E416", "#4BBA0F", "#447D87", "#2C24E9")) +
        theme_void()+
        theme(legend.position = "none")
dev.off()

pdf("v3/mcc_timecourse_v3_tricyclePosition_splitorig.pdf",height=4,width=14,useDingbats = F)
FeaturePlot(seur, "tricyclePosition",pt.size=1.5,raster=T,split.by = "orig.ident") &        
        scale_color_gradientn(colors=c("#2E22EA", "#9E3DFB", "#F86BE2", "#FCCE7B", "#C4E416", "#4BBA0F", "#447D87", "#2C24E9")) &
        theme_void()+
        theme(legend.position = "none")
dev.off()

DimPlot(seur, group.by = "CCStage",split.by="CCStage")


############################## SAVE OBJECT ##################################
saveRDS(seur, file="v3/mcc_timecourse_v3_13dim.rds")
############################################################################

##################### MULTICILAITED CELL SUBSETTING ##########################
DimPlot(seur, group.by="integrated_snn_res.0.3",label=T)
Idents(seur) <- "integrated_snn_res.0.3"
mccs = subset(seur, idents = c(0,8,9,4))

DefaultAssay(mccs) <- "integrated"
mccs = ScaleData(mccs)
mccs=RunPCA(mccs, npcs = 40)
ElbowPlot(mccs, ndims = 40)
mccs=RunUMAP(mccs,dims = 1:13)
mccs=FindNeighbors(mccs, dims = 1:13)
mccs=FindClusters(mccs,resolution =0.3)

DimPlot(mccs,label=T)
DefaultAssay(mccs) <- "RNA"
FeaturePlot(mccs, c("Mycl","Myb","Scgb3a2","Hey1"),order=T)
FeaturePlot(mccs, "tricyclePosition") +
        scale_color_gradientn(colors=c("#2E22EA", "#9E3DFB", "#F86BE2", "#FCCE7B", "#C4E416", "#4BBA0F", "#447D87", "#2C24E9"))

dir.create("v3/mcc_subset")
saveRDS(mccs, file="v3/mcc_subset/mcc_timecourse_v3_mcc_subset.rds")
mccs=readRDS("v3/mcc_subset/mcc_timecourse_v3_mcc_subset.rds")

DefaultAssay(mccs) <- "integrated"
mccs =FindClusters(mccs, resolution=0.2)
DimPlot(mccs, label=T,group.by="integrated_snn_res.0.3")

############ MCCS CLEAN #################
## unsure if a couple of clusters are mature MCCs transitioning to other states or doublets.

mccs=readRDS("v3/mcc_subset/mcc_timecourse_v3_mcc_subset.rds")
pdf("v3/mcc_subset/mcc_timecourse_v3_mcc_subset_clusters.pdf",height=8,width=11,useDingbats = F)
DimPlot(mccs, label=T,pt.size=1)+theme_void()
dev.off()
Idents(mccs) <- "integrated_snn_res.0.3"

weird_genes=c("Ecm1","Upk3bl","Krt4","Ltf","S100g","Agr2","Itln1","Mt1","Ascl1", "Calca","Cxcl13","Chga")

png("v3/mcc_subset/mcc_timecourse_v3_mcc_subset_weird_genes.png",height=800,width=800)
FeaturePlot(mccs, weird_genes) & theme_void()&theme(legend.position="none")
dev.off()

only_mccs=subset(mccs, idents=c(0:3))
DefaultAssay(only_mccs) = "integrated"
DimPlot(only_mccs)

only_mccs = ScaleData(only_mccs)
only_mccs=RunPCA(only_mccs, npcs = 40)
ElbowPlot(only_mccs, ndims=40)

only_mccs = RunUMAP(only_mccs, dims = 1:13)
only_mccs=FindNeighbors(only_mccs, dims=1:13)
only_mccs=FindClusters(only_mccs, resolution = 0.2)

pdf("v3/mccs_clean_subset/mccs_clean_cluster.pdf",height=8,width=11,useDingbats = F)
DimPlot(only_mccs, label=T,pt.size=1)+theme_void()
dev.off()


dir.create("v3/mccs_clean_subset")
saveRDS(only_mccs, file="v3/mccs_clean_subset/mccs_clean.rds")
only_mccs=readRDS("v3/mccs_clean_subset/mccs_clean.rds")


################# MITOTIC STEM CELL SUBSETTING #############

Idents(seur) <- "integrated_snn_res.0.3"
cycling = subset(seur, idents=c(1,5,6))
DimPlot(cycling)

DefaultAssay(cycling) <- "integrated"
cycling = ScaleData(cycling)
cycling=RunPCA(cycling, npcs = 40)
ElbowPlot(cycling, ndims=40)
cycling = RunUMAP(cycling, dims = 1:13)
cycling=FindNeighbors(cycling, dims=1:13)
cycling=FindClusters(cycling, resolution = 0.3)

DimPlot(cycling, label=T)
DefaultAssay(cycling) <- "RNA"
FeaturePlot(cycling, c("Krt5","Trp63","Mycl"))
FeaturePlot(cycling,"tricyclePosition")+
        scale_color_gradientn(colors=c("#2E22EA", "#9E3DFB", "#F86BE2", "#FCCE7B", "#C4E416", "#4BBA0F", "#447D87", "#2C24E9"))

## subset for just Krt5+ cells

FeatureScatter(cycling, "Krt5","Scgb3a1")
FeaturePlot(cycling, "Krt5",min.cutoff = 1.5)

k5=cycling["Krt5",]

k5_names=names(which(k5[["RNA"]]@data[1,] >1.5))

basal_cycling =subset(cycling, cells=k5_names)
DimPlot(basal_cycling)

DefaultAssay(basal_cycling) <- "integrated"

basal_cycling <- ScaleData(basal_cycling)
basal_cycling <- RunPCA(basal_cycling, npcs = 40)
ElbowPlot(basal_cycling, ndims = 40)

basal_cycling <- RunUMAP(basal_cycling, dims = 1:13)
basal_cycling <- FindNeighbors(basal_cycling, dims=1:13)
basal_cycling <- FindClusters(basal_cycling, resolution = 0.3)

DimPlot(basal_cycling,label=T)
DefaultAssay(basal_cycling) <- "RNA"
FeaturePlot(basal_cycling, c("Krt5","Scgb3a1","Scgb3a2"),order=T)
FeaturePlot(basal_cycling,"Krt5")
FeaturePlot(basal_cycling, "tricyclePosition")+
        scale_color_gradientn(colors=c("#2E22EA", "#9E3DFB", "#F86BE2", "#FCCE7B", "#C4E416", "#4BBA0F", "#447D87", "#2C24E9"))

dir.create("v3/cycling_basal_subset/")
saveRDS(basal_cycling, file="v3/cycling_basal_subset/mcc_timecourse_v3_basal_cycling.rds")
basal_cycling=readRDS("v3/cycling_basal_subset/mcc_timecourse_v3_basal_cycling.rds")

DefaultAssay(basal_cycling) <- "integrated"
basal_cycling <- FindClusters(basal_cycling, resolution = 0.1)
DimPlot(basal_cycling,label=T)

res0.1=basal_cycling@meta.data[,c("integrated_snn_res.0.1"),drop=F]
write.csv(res0.1,"v3/cycling_basal_subset/cycling_basal_res0.1.csv")


######################## PSEUDOTIME MULTICILIATED CELLS #####################

library(monocle3)
library(SeuratWrappers)

cds=as.cell_data_set(only_mccs)
cds=cluster_cells(cds)
cds=learn_graph(cds,use_partition = T)

plot_cells(cds)

cds=order_cells(cds)

cds_sub=choose_graph_segments(cds,clear_cds = F)
plot_cells(cds_sub)
cds_sub=order_cells(cds_sub)

plot_cells(cds_sub, color_cells_by = "pseudotime")

ps_df=as.data.frame(pseudotime(cds_sub))
ps_df$pseudo_bin = cut_interval(ps_df$`pseudotime(cds_sub)`, n=20,labels=F)

write.csv(ps_df, file="v3/mccs_clean_subset/mccs_clean_pseudotime_values.csv")

saveRDS(cds, file="v3/mccs_clean_subset/mccs_clean_monocle_object.rds")

## add to seurat object

only_mccs$pseudotime <- NA
only_mccs$pseudotime[match(rownames(ps_df),rownames(only_mccs@meta.data))] <- ps_df$`pseudotime(cds_sub)`

only_mccs$pseudo_bin<- NA
only_mccs$pseudo_bin[match(rownames(ps_df),rownames(only_mccs@meta.data))] <- ps_df$pseudo_bin

FeaturePlot(only_mccs, features="pseudotime")
DimPlot(only_mccs, group.by="pseudo_bin")
FeaturePlot(only_mccs, "tricyclePosition")
DimPlot(only_mccs, group.by="tricycleBinned")

saveRDS(only_mccs, file="v3/mccs_clean_subset/mccs_clean.rds")


####################### PSEUDOTIME MITOTIC STEM CELLS #######################

basal_cycling = readRDS("v3/cycling_basal_subset/mcc_timecourse_v3_basal_cycling.rds")

cds=as.cell_data_set(basal_cycling)
cds=cluster_cells(cds)
cds=learn_graph(cds,use_partition = T) #learn_graph_control = list(minimal_branch_len=20)

plot_cells(cds)

cds=order_cells(cds)

cds_sub=choose_graph_segments(cds,clear_cds = F)
plot_cells(cds_sub)
cds_sub=order_cells(cds_sub)

plot_cells(cds_sub, color_cells_by = "pseudotime")

ps_df=as.data.frame(pseudotime(cds))

ps_df$pseudo_cyclingbasal[match(names(pseudotime(cds_sub)),rownames(ps_df))] <- pseudotime(cds_sub)

write.csv(ps_df, file="v3/mcc_timecourse_v3_cyclingbasal_pseudotime.csv")

saveRDS(cds, file="v3/cycling_basal_subset/mcc_timecourse_v3_basal_cycling_monocle3.rds")
saveRDS(cds_sub, file="v3/cycling_basal_subset/mcc_timecourse_v3_Krt_cycling_monocle3.rds")
cds_sub=readRDS("v3/cycling_basal_subset/mcc_timecourse_v3_Krt_cycling_monocle3.rds")
cds=readRDS("v3/cycling_basal_subset/mcc_timecourse_v3_basal_cycling_monocle3.rds")
res0.1=read.csv("v3/cycling_basal_subset/cycling_basal_res0.1.csv")

####

pseudo =read.csv("v3/mcc_timecourse_v3_cyclingbasal_pseudotime.csv")
cycling_basal=readRDS("v3/cycling_basal_subset/mcc_timecourse_v3_basal_cycling.rds")

identical(rownames(cycling_basal@meta.data),pseudo$X)

cycling_basal$pseudo_cycling <- pseudo$pseudo_cyclingbasal

FeaturePlot(cycling_basal, "pseudo_cycling")


############## PLOTTING, ANALYSIS with datasets created above #######
library(Seurat)
library(dplyr)
library(ggplot2)
library(viridis)
library(cowplot)
library(grid)
library(ggpubr)

seur = readRDS("v3/mcc_timecourse_v3_13dim.rds")
only_mccs=readRDS("v3/mccs_clean_subset/mccs_clean.rds")
cycling_basal=readRDS("v3/cycling_basal_subset/mcc_timecourse_v3_basal_cycling.rds")


################# COLORS #######################
##tricycle colors
tricolors=c("#2E22EA", "#9E3DFB", "#F86BE2", "#FCCE7B", "#C4E416", "#4BBA0F", "#447D87", "#2C24E9")

mcc_color <- colorRampPalette(c("lightskyblue2", "royalblue4"))

colors=c("#009245","#F7A12D","darkgoldenrod","indianred",mcc_color(5)[5],"#996699","plum","#998675",mcc_color(5)[1],mcc_color(5)[3])

only_mccs_col=c(colors[1],mcc_color(6)[c(6,2,4)])

############## BIG DATASET - SUPPLEMENTARY ##################

pdf("v3/mcc_timecourse_v3_clusters.pdf",height=8,width=11,useDingbats = F)
DimPlot(seur, group.by="integrated_snn_res.0.3",cols = colors,pt.size=1) + scale_y_reverse()+scale_x_reverse()+ theme_void() + theme(legend.position = "none",title = element_blank())
dev.off()

pdf("v3/mcc_timecourse_v3_clusters_split.pdf",height=8,width=11,useDingbats = F)
DimPlot(seur, group.by="integrated_snn_res.0.3",cols = colors,pt.size=1,split.by="orig.ident",ncol = 2) + scale_y_reverse()+scale_x_reverse()+ theme_void() + theme(legend.position = "none",title = element_blank(),strip.text = element_blank())
dev.off()

DefaultAssay(seur) <- "RNA"

genes=c("Krt5","Scgb3a1","Deup1","Dnah5")
m=FeaturePlot(seur, features=genes,pt.size=1)&scale_color_viridis()&scale_x_reverse() &theme_void()


for(x in 1:4){
        
        pdf(paste0("v3/mcc_timecourse_",genes[[x]],".pdf"),height=8,width=11,useDingbats = F)
        print(FeaturePlot(seur, features=genes[[x]],pt.size=1)&scale_color_viridis()&scale_x_reverse() &scale_y_reverse()&theme_void() & theme(title=element_blank(),legend.position = "none"))
        dev.off()
        
        leg=get_legend(m[[x]])
        pdf(paste0("v3/mcc_timecourse_",genes[x],"_legend.pdf"),height=2,width=4,useDingbats = F)
        grid.newpage()
        grid.draw(leg)
        dev.off()
}
############### MONOCLE PLOTS ##################
library(monocle3)

cds_mccs=readRDS("v3/mccs_clean_subset/mccs_clean_monocle_object.rds")
cds_cycling=readRDS("v3/cycling_basal_subset/mcc_timecourse_v3_basal_cycling_monocle3.rds")

pdf("v3/mccs_clean_subset/mccs_clean_trajectory.pdf",height=8,width=11,useDingbats = F)
plot_cells(cds_mccs,color_cells_by = "integrated_snn_res.0.2",trajectory_graph_segment_size = 1,label_cell_groups = F,label_branch_points = F,label_leaves = F,label_principal_points = F,) + theme_void()+theme(legend.position = "none")+scale_x_reverse()+ggtitle("")
dev.off()

pdf("v3/mccs_clean_subset/mccs_clean_clusters.pdf",height=8,width=11,useDingbats = F)
DimPlot(only_mccs, group.by="integrated_snn_res.0.2",pt.size =1.5)+theme_void()+theme(legend.position = "none")+scale_x_reverse() +scale_color_manual(values=c("#009245",mcc_color(6)[c(6,2,4)]))+ggtitle("")
dev.off()

pdf("v3/mccs_clean_subset/mccs_clean_pseudotime.pdf",height=8,width=11,useDingbats = F)
FeaturePlot(only_mccs, "pseudotime",pt.size=1.5)+theme_void()+theme(legend.position = "none",title = element_blank())+scale_x_reverse() +scale_color_viridis(option = "C",direction = -1)
dev.off()

m=FeaturePlot(only_mccs, "pseudotime",pt.size=1.5)+theme_void()+theme(title = element_blank())+scale_x_reverse() +scale_color_viridis(option = "C",direction = -1)

library(cowplot)
library(grid)

leg=get_legend
pdf("v3/mccs_clean_subset/mccs_clean_pseudotime_legend.pdf",height=2,width=4,useDingbats = F)
grid.newpage()
grid.draw(leg)
dev.off()

### cycling basal

pdf("v3/cycling_basal_subset/cycling_basal_monocle_cluster_trajectory.pdf.pdf",height=8,width=11,useDingbats = F)
plot_cells(cds_cycling,color_cells_by = "integrated_snn_res.0.3",trajectory_graph_segment_size = 1,label_cell_groups = F,label_branch_points = F,label_leaves = F,label_principal_points = F,label_roots = F) + theme_void()+theme(legend.position = "none")+scale_y_reverse()+ggtitle("")
dev.off()

## use cluster ids from main seurat object
DimPlot(seur, label=T,group.by = "integrated_snn_res.0.3")
cycling_basal$main_clusters <- NA
cycling_basal$main_clusters[match(rownames(seur@meta.data[seur$integrated_snn_res.0.3==5,]),rownames(cycling_basal@meta.data))]<-"S"
cycling_basal$main_clusters[match(rownames(seur@meta.data[seur$integrated_snn_res.0.3==6,]),rownames(cycling_basal@meta.data))]<-"G2M"
cycling_basal$main_clusters[match(rownames(seur@meta.data[seur$integrated_snn_res.0.3==1,]),rownames(cycling_basal@meta.data))]<-"basal"

pdf("v3/cycling_basal_subset/basal_cycling_clusters.pdf",height=8,width=11,useDingbats = F)
DimPlot(cycling_basal,label=F,group.by="main_clusters",pt.size=1.5)+
        scale_color_manual(values=colors[c(2,7,6)])+
        theme_void()+
        theme(legend.position = "none",title = element_blank())+
        scale_y_reverse()
dev.off()

pdf("v3/cycling_basal_subset/basal_cycling_pseudotime.pdf",height=8,width=11,useDingbats = F)
FeaturePlot(cycling_basal, "pseudo_cycling",pt.size=1.5)+theme_void()+theme(legend.position = "none",title = element_blank())+scale_y_reverse() +scale_color_viridis(option = "C",direction = -1)
dev.off()

f=FeaturePlot(cycling_basal, "pseudo_cycling",pt.size=1.5)+theme_void()+theme(title = element_blank())+scale_x_reverse() +scale_color_viridis(option = "C",direction = -1)

leg=get_legend(f)
pdf("v3/cycling_basal_subset/cycling_basal_pseudotime_legend.pdf",height=2,width=4,useDingbats = F)
grid.newpage()
grid.draw(leg)
dev.off()


############ HIGHLIGHT CELLS ON MAIN DATASET #############

seur$cycling_basal_cells <- NA
seur$cycling_basal_cells[match(colnames(cycling_basal),colnames(seur))]<- "cycling_basal"
seur$only_mccs <- NA
seur$only_mccs[match(colnames(only_mccs),colnames(seur))]<- "MCCs"

pdf("v3/cycling_basal_subset/cycling_basal_on_original.pdf",height=8,width=11,useDingbats = F)
DimPlot(seur,group.by="cycling_basal_cells",pt.size=1.5,raster=T) +scale_color_manual(values="#F7A12D","grey")+theme_void()+theme(legend.position = "none") + ggtitle("")
dev.off()

pdf("v3/mccs_clean_subset/mccs_clean_on_original.pdf",height=8,width=11,useDingbats = F)
DimPlot(seur, group.by="only_mccs",pt.size=1.5,)+scale_color_manual(values=mcc_color(6)[3],"grey") + theme_void()+ggtitle("")+theme(legend.position = "none")
dev.off()

############### TRICYCLE PLOTS #################

pdf("v3/cycling_basal_subset/cycling_basal_tricyclePosition.pdf",height=8,width=11,useDingbats = F)
FeaturePlot(cycling_basal, "tricyclePosition",pt.size=2) + scale_color_gradientn(colors=c("#2E22EA", "#9E3DFB", "#F86BE2", "#FCCE7B", "#C4E416", "#4BBA0F", "#447D87", "#2C24E9")) +theme_void()+theme(legend.position = "none")+ggtitle("")+scale_y_reverse()
dev.off()

pdf("v3/mccs_clean_subset/mccs_clean_tricyclePosition.pdf",height=8,width=11,useDingbats = F)
FeaturePlot(only_mccs, "tricyclePosition",pt.size=2) + scale_color_gradientn(colors=c("#2E22EA", "#9E3DFB", "#F86BE2", "#FCCE7B", "#C4E416", "#4BBA0F", "#447D87", "#2C24E9")) +theme_void()+theme(legend.position = "none")+ggtitle("")+scale_x_reverse()
dev.off()

pdf("v3/mcc_timecourse_tricyclePosition.pdf",height=8,width=11,useDingbats = F)
FeaturePlot(seur, "tricyclePosition",pt.size=2) + scale_color_gradientn(colors=c("#2E22EA", "#9E3DFB", "#F86BE2", "#FCCE7B", "#C4E416", "#4BBA0F", "#447D87", "#2C24E9")) +theme_void()+theme(legend.position = "none")+ggtitle("")+scale_y_reverse()+scale_x_reverse()
dev.off()

############ HIGHLIGHT CELLS ON MAIN DATASET #############

seur$cycling_basal_cells <- NA
seur$cycling_basal_cells[match(colnames(cycling_basal),colnames(seur))]<- "cycling_basal"
seur$only_mccs <- NA
seur$only_mccs[match(colnames(only_mccs),colnames(seur))]<- "MCCs"

pdf("v3/cycling_basal_subset/cycling_basal_on_original.pdf",height=8,width=11,useDingbats = F)
DimPlot(seur,group.by="cycling_basal_cells",pt.size=1.5,raster=T) +scale_color_manual(values="#F7A12D","grey")+theme_void()+theme(legend.position = "none") + ggtitle("")
dev.off()

pdf("v3/mccs_clean_subset/mccs_clean_on_original.pdf",height=8,width=11,useDingbats = F)
DimPlot(seur, group.by="only_mccs",pt.size=1.5,)+scale_color_manual(values=mcc_color(6)[3],"grey") + theme_void()+ggtitle("")+theme(legend.position = "none")
dev.off()


################ Pseudotime vs Tricycle #################

dat=cycling_basal@meta.data[,c("pseudo_cycling","tricyclePosition","main_clusters")]

cyc=ggplot(dat %>% filter(!is.na(pseudo_cycling)), aes(x=tricyclePosition,y=pseudo_cycling,color=main_clusters))+
        geom_point(size=1.5)+
        scale_color_manual(values=colors[c(2,7,6)])+
        theme_classic()+
        xlab("Tricycle Position")+
        ylab("Pseudotime")+
        geom_vline(xintercept = pi/2,linetype="dashed")+
        geom_vline(xintercept=pi,linetype="dashed")+
        geom_vline(xintercept=pi+pi*3/4,linetype="dashed")+
        scale_x_continuous(breaks=c(pi/4,pi*3/4,pi+pi*3/8,pi+pi),
                           labels=c("G0/G1", "S", "G2M","G0/G1"))+
        theme(legend.position="none",axis.text = element_text(size=15,color="black"),axis.title = element_text(size=17))

dat_mccs=only_mccs@meta.data[,c("pseudotime","tricyclePosition","integrated_snn_res.0.2")]
mc=ggplot(dat_mccs %>% filter(!is.na(pseudotime)), aes(x=tricyclePosition,y=pseudotime,color=integrated_snn_res.0.2))+
        geom_point(size=1.5)+
        scale_color_manual(values=only_mccs_col)+
        theme_classic()+
        xlab("Tricycle Position")+
        ylab("Pseudotime")+
        geom_vline(xintercept = pi/2,linetype="dashed")+
        geom_vline(xintercept=pi,linetype="dashed")+
        geom_vline(xintercept=pi+pi*3/4,linetype="dashed")+
        scale_x_continuous(breaks=c(pi/4,pi*3/4,pi+pi*3/8,pi+pi),
                           labels=c("G0/G1", "S", "G2M","G0/G1"))+
        theme(legend.position="none",axis.text = element_text(size=15,color="black"),axis.title = element_text(size=17))

pdf("v3/cycling_mccs_tricycle_vs_pseudotime.pdf",height=5,width=4,useDingbats = F)
ggarrange(cyc,mc,ncol=1)
dev.off()


######################### DIFFERENTIAL GENE EXPRESSION #######################
library(data.table)
library(pheatmap)
goterms = read.csv("v3/cellcycle_GO.txt",sep="\t",header = F)
cc_genes = unique(goterms$V2)

sgenes=read.csv("~/Documents/Reiter_Seq/s_phase_human_mgi_genes.csv")
g2mgenes=read.csv("~/Documents/Reiter_Seq/g2m_phase_human_mgi_genes.csv")

s=sgenes$MGI.symbol
g2m=g2mgenes$MGI.symbol

total_cc = unique(c(cc_genes,s,g2m))
write.csv(total_cc, file="v3/cellcycle_genes_for_DE.csv")
DimPlot(seur, label=T)

FeaturePlot(seur, "tricyclePosition",label=T)

meta=seur@meta.data
meta$pseudo_mcc = NA
meta$pseudo_mcc[match(rownames(only_mccs@meta.data),rownames(meta))]<-only_mccs$pseudotime
meta$pseudo_bin_mcc=NA
meta$pseudo_bin_mcc[match(rownames(only_mccs@meta.data),rownames(meta))]<-only_mccs$pseudo_bin

seur$pseudo_bin_mcc <-meta$pseudo_bin_mcc
seur$pseudo_mcc <- meta$pseudo_mcc
DimPlot(seur, group.by="pseudo_bin_mcc")
DimPlot(seur, group.by="pseudo_bin_cycling")

### group cells by phase from tricycle
meta=seur@meta.data
meta_filt = meta %>% filter(!is.na(pseudo_mcc))
meta_filt$tricycle_celltype <- "mcc_G1/G0"
meta_filt$tricycle_celltype[meta_filt$tricyclePosition > pi/2 & meta_filt$tricyclePosition < pi] <- "mcc_S"
meta_filt$tricycle_celltype[meta_filt$tricyclePosition >= pi & meta_filt$tricyclePosition < pi*7/4] <- "mcc_G2M"

meta_cyc=meta %>% filter(!is.na(pseudo_cycling))
meta_cyc$tricycle_celltype <- "cyc_G1/G0"
meta_cyc$tricycle_celltype[meta_cyc$tricyclePosition > pi/2 & meta_cyc$tricyclePosition < pi] <- "cyc_S"
meta_cyc$tricycle_celltype[meta_cyc$tricyclePosition >= pi & meta_cyc$tricyclePosition < pi*7/4] <- "cyc_G2M"

##add cluster ids from MCCs
seur$mcc_cluster <- NA
seur$mcc_cluster[match(rownames(only_mccs@meta.data),rownames(seur@meta.data))]<-only_mccs$integrated_snn_res.0.2

seur$tricycle_celltype <-NA
seur$tricycle_celltype[match(rownames(meta_filt),rownames(seur@meta.data))]<-meta_filt$tricycle_celltype
seur$tricycle_celltype[match(rownames(meta_cyc),rownames(seur@meta.data))]<-meta_cyc$tricycle_celltype

DimPlot(seur, group.by="tricycle_celltype",label=T)


cc =read.csv(file="v3/cellcycle_genes_for_DE.csv")
total_cc=cc$x
seur_sub=seur
seur_sub[["RNA"]]= subset(seur_sub[["RNA"]], 
                          features = total_cc)
DefaultAssay(seur_sub) <- "RNA"
Idents(seur_sub) <- "tricycle_celltype"
sphase=FindMarkers(seur_sub,assay="RNA",ident.1 = "mcc_S",ident.2="cyc_S")
g2mphase=FindMarkers(seur_sub,assay="RNA",ident.1="mcc_G2M",ident.2 = "cyc_G2M")
g1g0=FindMarkers(seur_sub,assay="RNA",ident.1="mcc_G1/G0",ident.2="cyc_G1/G0")

#write.csv(sphase,"v3/mccs_clean_subset/mccs_clean_MCC_vs_basal_Sphase_genes.csv")
#write.csv(g2mphase,"v3/mccs_clean_subset/mccs_clean_MCC_vs_basal_G2Mphase_genes.csv" )
#write.csv(g1g0,"v3/mccs_clean_subset/mccs_clean_MCC_vs_basal_G1G0phase_genes.csv")

sphase=read.csv("v3/mccs_clean_subset/mccs_clean_MCC_vs_basal_Sphase_genes.csv",row.names = 1)
g2mphase=read.csv("v3/mccs_clean_subset/mccs_clean_MCC_vs_basal_G2Mphase_genes.csv",row.names=1)
g1g0=read.csv("v3/mccs_clean_subset/mccs_clean_MCC_vs_basal_G1G0phase_genes.csv",row.names=1)

sphase_filt=sphase %>% filter(abs(avg_log2FC) > log2(1.5)) %>% filter(p_val_adj < .05)
g2mphase_filt=g2mphase %>% filter(abs(avg_log2FC) > log2(1.5)) %>% filter(p_val_adj < .05)
g1g0_filt=g1g0 %>% filter(abs(avg_log2FC) > log2(1.5)) %>% filter(p_val_adj < .05)

de_list = unique(c(rownames(sphase_filt),rownames(g2mphase_filt),rownames(g1g0_filt)))

seur$tricycle_celltype <- factor(seur$tricycle_celltype,levels=c("cyc_G1/G0","cyc_S","cyc_G2M","mcc_G1/G0","mcc_S","mcc_G2M",NA))
exp=AverageExpression(seur,assays = "RNA",features=de_list,group.by="tricycle_celltype")
dat=exp$RNA

k=6
out=pheatmap(dat,cluster_cols = F,scale="row",color = PurpleAndYellow(),cutree_rows = k)

gene_ids=sort(cutree(out$tree_row, k=k))

gene_ids_ord=gene_ids[match(rownames(dat)[out$tree_row$order],names(gene_ids))]

write.csv(gene_ids_ord, file="v3/mccs_clean_subset/DEgenes_cellcycle_mcc_vs_cycling_heatmap_genes.csv")

### annotations
anno=as.data.frame(colnames(dat))
colnames(anno) = "phase"
rownames(anno) = anno$phase

tri=colorRampPalette(tricolors)(20)
anno_col_color=list(phase=c(tri[1],tri[8],tri[12],tri[1],tri[8],tri[12]))
names(anno_col_color$phase) <- colnames(dat)

pdf("v3/mccs_clean_subset/DEgenes_G1_S_G2M_cycling_vs_MCC_heatmap.pdf",width=4,height=4,useDingbats = F)
pheatmap(dat,scale = "row",color = PurpleAndYellow(),cluster_cols = F, cutree_rows = k,show_rownames = F,annotation_col = anno,annotation_legend = F,annotation_colors = anno_col_color,annotation_names_col = F,show_colnames = T,gaps_col=3)
dev.off()


colnames(sphase) <- paste0("S_",colnames(sphase))
sphase$gene<-rownames(sphase)

colnames(g2mphase)<-paste0("G2M_",colnames(g2mphase))
g2mphase$gene <-rownames(g2mphase)

colnames(g1g0)<-paste0("G1G0_",colnames(g1g0))
g1g0$gene<-rownames(g1g0)
full_dat=merge(sphase,g2mphase,by ="gene",all=T )
full_dat=merge(full_dat,g1g0,by="gene",all=T)

gene_id_df=as.data.frame(gene_ids_ord)
gene_id_df$gene <- rownames(gene_id_df)
## add labels to count clusters down heatmap because it is hard to keep track of arbitrary numbering
gene_id_df$heatmap_rowclus_order <- NA
gene_id_df$heatmap_rowclus_order[gene_id_df$gene_ids_ord == 6]<-1
gene_id_df$heatmap_rowclus_order[gene_id_df$gene_ids_ord == 4]<-2
gene_id_df$heatmap_rowclus_order[gene_id_df$gene_ids_ord == 3]<-3
gene_id_df$heatmap_rowclus_order[gene_id_df$gene_ids_ord == 2]<-4
gene_id_df$heatmap_rowclus_order[gene_id_df$gene_ids_ord == 5]<-5
gene_id_df$heatmap_rowclus_order[gene_id_df$gene_ids_ord == 1]<-6



full_dat_order=merge(gene_id_df %>% select(-gene_ids_ord),full_dat,by="gene",all=T)
full_dat_order=full_dat_order[match(names(gene_ids_ord),full_dat_order$gene),]

##reorder gene clusters

clus1=gene_id_df$gene[gene_id_df$heatmap_rowclus_order==3]
clus2=gene_id_df$gene[gene_id_df$heatmap_rowclus_order==2]
clus3=gene_id_df$gene[gene_id_df$heatmap_rowclus_order==1]
clus4=gene_id_df$gene[gene_id_df$heatmap_rowclus_order==4]
clus5=gene_id_df$gene[gene_id_df$heatmap_rowclus_order==5]
clus6=gene_id_df$gene[gene_id_df$heatmap_rowclus_order==6]


all_clus=c(clus1,clus2,clus3,clus4,clus5,clus6)

write.csv(all_clus, file="v3/mccs_clean_subset/DEgenes_cellcycle_mcc_vs_cycling_heatmap_genes.csv")
all_clus=read.csv("v3/mccs_clean_subset/DEgenes_cellcycle_mcc_vs_cycling_heatmap_genes.csv")

dat_reorder=dat[match(all_clus,rownames(dat)),]
### annotations

anno=as.data.frame(colnames(dat_reorder))
rownames(anno) = anno[,1]
anno$group <- "Cycling basal cells"
anno$group[grep("mcc*",rownames(anno))]<-"Multiciliated cells"
anno=anno[,-1,drop=F]

tri=colorRampPalette(tricolors)(20)
anno_col_color=list(phase=c(tri[2],tri[2],tri[8],tri[8],tri[12],tri[12]))
names(anno_col_color$phase) <- colnames(dat)

anno_col_color[["group"]]=group_col=c(colors[2],mcc_color(5)[3])
names(anno_col_color[["group"]]) <- c("Cycling basal cells","Multiciliated cells")

pdf("v3/mccs_clean_subset/DEgenes_G1_S_G2M_cycling_vs_MCC_heatmap_v2.pdf",width=4,height=4,useDingbats = F)
pheatmap(dat_reorder,scale = "row",color = PurpleAndYellow(),cluster_cols = F, cluster_rows = F,cutree_rows = k,show_rownames = F,annotation_col = anno,annotation_legend = F,annotation_colors = anno_col_color,annotation_names_col = F,show_colnames = F,gaps_col=c(2,4),gaps_row=c(length(clus1),61,123,172,177))
dev.off()

## DE lists in order of heatmap for supp table

sphase_ord = sphase_filt[match(all_clus,rownames(sphase_filt)),]
g2m_ord = g2mphase_filt[match(all_clus,rownames(g2mphase_filt)),]
g1g0_ord=g1g0_filt[match(all_clus,rownames(g1g0_filt)),]

rownames(sphase_ord) <- all_clus
rownames(g2m_ord) <- all_clus
rownames(g1g0_ord) <- all_clus

colnames(sphase_ord) <-paste0("S_",colnames(sphase_ord))
colnames(g2m_ord) <-paste0("G2/M_",colnames(g2m_ord))
colnames(g1g0_ord) <-paste0("G1/G0_",colnames(g1g0_ord))

heatmap_de=cbind(g1g0_ord,sphase_ord)
heatmap_de=cbind(heatmap_de, g2m_ord)

heatmap_de$GroupID <- 1
heatmap_de$GroupID[rownames(heatmap_de) %in% clus2]<-2
heatmap_de$GroupID[rownames(heatmap_de) %in% clus3]<-3
heatmap_de$GroupID[rownames(heatmap_de) %in% clus4]<-4
heatmap_de$GroupID[rownames(heatmap_de) %in% clus5]<-5
heatmap_de$GroupID[rownames(heatmap_de) %in% clus6]<-6

write.csv(heatmap_de, file="v3/mccs_clean_subset/heatmapDEgenes_G1_S_G2M_cycling_vs_MCC_v2.csv")

write.csv(heatmap_de,"~/Box Sync/E2f7_paper/Supplementary_Table2.csv")



##### individual genes over tricycle phase

## E2f7 and Mcm gene
genes=c("E2f7","Gmnn","Ranbp1","Mcm2","Mcm3","Mcm4","Mcm5","Mcm6","Mcm7")
 cyc_gene_avg =AverageExpression(cycling_basal,assay="RNA",features=genes,group.by="tricycleBin")
 cyc_plot=cyc_gene_avg$RNA
 colnames(cyc_plot) <- paste0(colnames(cyc_plot),"_cyc")
 mmc_gene_avg=AverageExpression(mccs,assay="RNA",features=genes,group.by="tricycleBinned")
mcc_plot=mmc_gene_avg$RNA
colnames(mcc_plot) <- paste0(colnames(mcc_plot), "_mcc")

indiv_dat=cbind(cyc_plot,mcc_plot)
dat_melt=reshape2::melt(indiv_dat)
dat_melt$cells <- "Basal"
dat_melt$cells[grep("mcc",dat_melt$Var2)]<- "Multiciliated"
library(stringr)

dat_melt$tricycleBin <- str_remove(dat_melt$Var2,"_cyc")
dat_melt$tricycleBin <- str_remove(dat_melt$tricycleBin,"_mcc")
dat_melt$tricycleBin <- as.numeric(as.character(dat_melt$tricycleBin))

pdf("v3/E2f7_sig_basal_vs_mcc_lineplots.pdf",height=8,width=7,useDingbats = F)
ggplot(dat_melt, aes(x=tricycleBin,y=(value),color=cells))+
        geom_point(size=2)+
        geom_line(linewidth=1)+
        scale_color_discrete(name="", labels=c("Cycling basal cells","Multiciliated cells"))+
        scale_color_manual(values=c(colors[2],mcc_color(5)[3]))+
        ylab("Gene Expression")+
        xlab("Tricycle Bin")+
        geom_vline(xintercept=6,linetype="dashed")+
        geom_vline(xintercept = 11,linetype="dashed")+
        geom_vline(xintercept=18,linetype="dashed")+
        scale_x_continuous(breaks=c(3,8.5,14.5,20),
                           labels=c("G0/G1", "S", "G2M","G0/G1"))+
        theme_classic()+
        theme(axis.ticks.x = element_blank(), axis.text=element_text(color="black",size=12),axis.title = element_text(color="black",size=14),strip.background = element_blank(),strip.text.x = element_text(size=12,color="black",face = "italic"),legend.position = "top",axis.text.x = element_text(angle = 45,vjust = 0.9,hjust=0.9))+
        facet_wrap(~Var1,scale="free")
dev.off()  


   


genes=c(shared_s,shared_g2m)
gene_exp=AverageExpression(mccs,assays = "RNA",features = c("Hells","Pcna","Top2a","Aurka"),group.by = "pseudo_bin_mcc")
library(lemon)
gene_exp_dat=gene_exp$RNA
gene_exp_melt=reshape2::melt(gene_exp_dat)
gene_exp_melt$stage <- "G2M"
gene_exp_melt$stage[gene_exp_melt$Var1 %in% c("Hells","Pcna")]<-"S"
m=ggplot(gene_exp_melt,aes(x=Var2,y=log1p(value),color=Var1))+
        geom_point(size=3.5)+
        geom_line(linewidth=1.5)+
        ylab("log(average expression)")+
        expand_limits( y = 0)+
        xlab("Pseudotime Bin")+
        theme_classic()+
        facet_wrap(~Var1,ncol = 2)+
        scale_color_manual(values=RColorBrewer::brewer.pal(4,"Set1"))+
        theme(axis.text.x = element_blank(),axis.ticks.x=element_blank(), axis.text.y=element_text(size=20),axis.title = element_text(size=22),axis.text=element_text(color="black"))

g1 <- ggplot(gene_exp_melt %>% filter(Var1 %in% c("Hells","Pcna")),aes(x=Var2,y=log1p(value),color=Var1))+
        geom_point(size=3.5)+
        geom_line(linewidth=1.5)+
        expand_limits( y = 0)+
        theme_classic()+
        facet_wrap(~Var1)+
        scale_color_manual(values=RColorBrewer::brewer.pal(4,"Set1")[1:2])+
        theme(axis.text.x = element_blank(),axis.ticks.x=element_blank(), axis.text.y=element_text(size=16),axis.title = element_blank(),axis.text=element_text(color="black"),legend.position = "none",strip.background = element_blank())

g2 <- ggplot(gene_exp_melt %>% filter(Var1 %in% c("Top2a","Aurka")),aes(x=Var2,y=log1p(value),color=Var1))+
        geom_point(size=3.5)+
        geom_line(linewidth=1.5)+
        expand_limits( y = 0)+
        theme_classic()+
        facet_wrap(~Var1,)+
        scale_color_manual(values=RColorBrewer::brewer.pal(4,"Set1")[3:4])+
        theme(axis.text.x = element_blank(),axis.ticks.x=element_blank(), axis.text.y=element_text(size=16),axis.title = element_blank(),axis.text=element_text(color="black"),legend.position = "none",strip.background = element_blank())

pdf("v3/mcc_subset/mcc_subset_hells_pcna_top2a_aurka_pseudotime.pdf",height=5,width=5,useDingbats = F)
grid.arrange(g1, g2, nrow=2)
dev.off()


pdf(paste0("v3/mcc_subset/mccs_multigene_pseudobin.pdf"),height=4,width=5,useDingbats = F)
m+theme(legend.position = "none")
dev.off()

cyc_gene_exp=AverageExpression(cycling_basal,assays = "RNA",features = genes,group.by = "pseudo_bin_cycling")

cyc_gene_exp_dat=cyc_gene_exp$RNA
cyc_gene_exp_melt=reshape2::melt(cyc_gene_exp_dat)

ggplot(cyc_gene_exp_melt,aes(x=Var2,y=log1p(value),color=Var1))+
        geom_point(size=3.5)+
        geom_line(linewidth=1.5)+
        ylab("log(average expression)")+
        expand_limits( y = 0)+
        xlab("Pseudotime Bin")+
        theme_classic()+
        facet_wrap(~Var1)+
        #scale_color_manual(values=RColorBrewer::brewer.pal(4,"Set1"))+
        theme(axis.text.x = element_blank(),axis.ticks.x=element_blank(), axis.text.y=element_text(size=20),axis.title = element_text(size=22),axis.text=element_text(color="black"))

VlnPlot(seur, features=c("S.Score","G2M.Score"),group.by = "tricycle_phase")


################# SIMILARITIES BETWEEN CELL CYCLE ###############

cc =read.csv(file="v3/cellcycle_genes_for_DE.csv")
total_cc=cc$x

mccs_sub=only_mccs
mccs_sub[["RNA"]]= subset(mccs_sub[["RNA"]], 
                          features = total_cc)

meta_mccs=mccs_sub@meta.data
meta_mccs = meta_mccs %>% filter(!is.na(pseudotime))
meta_mccs$tricycle_phase <- "mcc_G1/G0"
meta_mccs$tricycle_phase[meta_mccs$tricyclePosition > pi/2 & meta_mccs$tricyclePosition < pi] <- "mcc_S"
meta_mccs$tricycle_phase[meta_mccs$tricyclePosition >= pi & meta_mccs$tricyclePosition < pi*7/4] <- "mcc_G2M"

mccs_sub$tricycle_phase <- NA
mccs_sub$tricycle_phase[match(rownames(meta_mccs),rownames(mccs_sub@meta.data))]<-meta_mccs$tricycle_phase

Idents(mccs_sub) <- "tricycle_phase"
DimPlot(mccs_sub, group.by="tricycle_phase")

inter=(cut_interval(cycling_basal$tricyclePosition,n=20,labels=F))
cycling_basal$tricycleBin <- inter

cyc_sub=cycling_basal
cyc_sub[["RNA"]]= subset(cyc_sub[["RNA"]], 
                         features = total_cc)

meta_cyc=cyc_sub@meta.data
meta_cyc = meta_cyc %>% filter(!is.na(pseudo_cycling))
meta_cyc$tricycle_phase <- "cyc_G1/G0"
meta_cyc$tricycle_phase[meta_cyc$tricyclePosition > pi/2 & meta_cyc$tricyclePosition < pi] <- "cyc_S"
meta_cyc$tricycle_phase[meta_cyc$tricyclePosition >= pi & meta_cyc$tricyclePosition < pi*7/4] <- "cyc_G2M"

cyc_sub$tricycle_phase <- NA
cyc_sub$tricycle_phase[match(rownames(meta_cyc),rownames(cyc_sub@meta.data))]<-meta_cyc$tricycle_phase

Idents(cyc_sub) <- "tricycle_phase"
DimPlot(cyc_sub, group.by="tricycle_phase")

mcc_sphase=FindMarkers(mccs_sub, ident.1="mcc_S",ident.2 = c("mcc_G2M","mcc_G1/G0"),assay="RNA",only.pos = T)

cyc_sphase=FindMarkers(cyc_sub, ident.1="cyc_S",ident.2=c("cyc_G2M","cyc_G1/G0"),assay="RNA",only.pos = T)


#write.csv(mcc_sphase,"v3/mccs_clean_subset/mccs_clean_S_vs_G2M_G0G1_markers.csv")
#write.csv(cyc_sphase, "v3/cycling_basal_subset/cycling_basal_S_vs_G2M_G0G1_markers.csv")
mcc_sphase=read.csv("v3/mccs_clean_subset/mccs_clean_S_vs_G2M_G0G1_markers.csv",row.names = 1)
cyc_sphase=read.csv("v3/cycling_basal_subset/cycling_basal_S_vs_G2M_G0G1_markers.csv",row.names = 1)

mcc_thresh= mcc_sphase %>% filter(p_val_adj < .05) %>% filter(avg_log2FC > log2(1.5))
cyc_thresh = cyc_sphase %>% filter(p_val_adj < .05) %>% filter(avg_log2FC > log2(1.5))

common_S=intersect(rownames(mcc_thresh),rownames(cyc_thresh))

mcc_g2mphase=FindMarkers(mccs_sub, ident.1="mcc_G2M",ident.2 = c("mcc_S","mcc_G1/G0"),assay="RNA",only.pos = T)

cyc_g2mphase=FindMarkers(cyc_sub, ident.1="cyc_G2M",ident.2=c("cyc_S","cyc_G1/G0"),assay="RNA",only.pos = T)

#write.csv(mcc_g2mphase, "v3/mccs_clean_subset/mccs_clean_G2M_vs_S_G0G1_markers.csv")
#write.csv(cyc_g2mphase,"v3/cycling_basal_subset/cycling_basal_G2M_vs_S_G0G1_markers.csv")

mcc_g2mphase=read.csv("v3/mccs_clean_subset/mccs_clean_G2M_vs_S_G0G1_markers.csv",row.names=1)
cyc_g2mphase=read.csv("v3/cycling_basal_subset/cycling_basal_G2M_vs_S_G0G1_markers.csv",row.names=1)

mcc_g2mthresh= mcc_g2mphase %>% filter(p_val_adj < .05) %>% filter(avg_log2FC > log2(1.5))
cyc_g2mthresh = cyc_g2mphase %>% filter(p_val_adj < .05) %>% filter(avg_log2FC > log2(1.5))

common_g2m=intersect(rownames(mcc_g2mthresh),rownames(cyc_g2mthresh))

mcc_g0=FindMarkers(mccs_sub, ident.1="mcc_G1/G0",ident.2 = c("mcc_S","mcc_G2M"),assay="RNA",only.pos = T)
cyc_g0=FindMarkers(cyc_sub, ident.1="cyc_G1/G0",ident.2 = c("cyc_S","cyc_G2M"),assay="RNA",only.pos = T)

#write.csv(mcc_g0, "v3/mccs_clean_subset/mccs_clean_G0G1_vs_S_G2M_markers.csv")
#write.csv(cyc_g0,"v3/cycling_basal_subset/cycling_basal_G0G1_vs_S_G2M_markers.csv")

mcc_g0=read.csv("v3/mccs_clean_subset/mccs_clean_G0G1_vs_S_G2M_markers.csv",row.names = 1)
cyc_g0=read.csv("v3/cycling_basal_subset/cycling_basal_G0G1_vs_S_G2M_markers.csv",row.names=1)

mcc_g0_thresh= mcc_g0 %>% filter(p_val_adj < .05) %>% filter(avg_log2FC > log2(1.5))
cyc_g0_thresh=cyc_g0 %>% filter(p_val_adj < .05) %>% filter(avg_log2FC > log2(1.5))

g0_common = intersect(rownames(mcc_g0_thresh),rownames(cyc_g0_thresh))

cyc_g2m=AverageExpression(cycling_basal,assays = "RNA",features = c(common_S,common_g2m),group.by = "tricycleBin")
cyc_g2m=cyc_g2m$RNA

mcc_g2m=AverageExpression(only_mccs,assays = "RNA",features = c(common_S,common_g2m),group.by = "tricycleBinned")
mcc_g2m=mcc_g2m$RNA

colnames(cyc_g2m) <- paste0(colnames(cyc_g2m),"_cyc")
colnames(mcc_g2m)<-paste0(colnames(mcc_g2m),"_mcc")

dat=cbind(cyc_g2m,mcc_g2m)

anno=as.data.frame(colnames(dat))
colnames(anno) = "Tricycle"
rownames(anno) = anno$Tricycle

clr=colorRampPalette(tricolors)(20)
names(clr) = colnames(mcc_g2m)

cl2=colorRampPalette(tricolors)(20)
names(cl2)=colnames(cyc_g2m)
clr=list(Tricycle=c(clr,cl2))

binned_col=colorRampPalette(tricolors)(20)

clr[["Phase"]]<-c(binned_col[1],binned_col[8],binned_col[14])
names(clr[["Phase"]])<-c("G1/G0","S","G2M")
levels(cut_interval(cycling_basal$tricyclePosition,n=20))

library(pheatmap)

pdf("v3/combined_mcc_cyc_S_G2M_heatmap.pdf",height=4,width=6,useDingbats = F)
pheatmap(dat,cluster_cols = F,cluster_rows = F,scale = "row",color = PurpleAndYellow(),border_color = NA,gaps_row = 6,gaps_col=20,annotation_col = anno,annotation_colors = clr,annotation_names_col = F,show_colnames = F,annotation_legend = F)
dev.off()


################ GENE EXPRESSION PLOTS #############
## s phase - Gmnn, Mcm3, Mcm5
## g2m phase - Kif23, Racgap1, Ect2, Prc1
## potential regulators Cdkn1a,Ccno,E2f7

inter=(cut_interval(cycling_basal$tricyclePosition,n=20,labels=F))
cycling_basal$tricycleBin <- inter

##use three genes each - across rows

genes=c("Gmnn","Kif23","Ccno","Gins2","Racgap1","Cdkn1a","Mcm5","Ect2","E2f7")
#genes=c("Plk4","Sass6","Deup1")

cyc_gene_avg =AverageExpression(cycling_basal,assay="RNA",features=genes,group.by="tricycleBin")
cyc_plot=cyc_gene_avg$RNA
colnames(cyc_plot) <- paste0(colnames(cyc_plot),"_cyc")
mmc_gene_avg=AverageExpression(only_mccs,assay="RNA",features=genes,group.by="tricycleBinned")
mcc_plot=mmc_gene_avg$RNA
colnames(mcc_plot) <- paste0(colnames(mcc_plot), "_mcc")

indiv_dat=cbind(cyc_plot,mcc_plot)
dat_melt=reshape2::melt(indiv_dat)
dat_melt$cells <- "Basal"
dat_melt$cells[grep("mcc",dat_melt$Var2)]<- "Multiciliated"
library(stringr)

dat_melt$tricycleBin <- str_remove(dat_melt$Var2,"_cyc")
dat_melt$tricycleBin <- str_remove(dat_melt$tricycleBin,"_mcc")
dat_melt$tricycleBin <- as.numeric(as.character(dat_melt$tricycleBin))


## change pdf title and size for different gene sets
## for plk4, sass6, and deup1 - height=3, called lineplots2
pdf("v3/mccs_clean_subset/basal_vs_mcc_lineplots.pdf",height=8,width=7,useDingbats = F)
ggplot(dat_melt, aes(x=tricycleBin,y=(value),color=cells))+
        geom_point(size=2)+
        geom_line(linewidth=1)+
        scale_color_discrete(name="", labels=c("Cycling basal cells","Multiciliated cells"))+
        scale_color_manual(values=c(colors[2],mcc_color(5)[3]))+
        ylab("Gene Expression")+
        xlab("Tricycle Bin")+
        geom_vline(xintercept=6,linetype="dashed")+
        geom_vline(xintercept = 11,linetype="dashed")+
        geom_vline(xintercept=17,linetype="dashed")+
        scale_x_continuous(breaks=c(3,8.5,14.5,19.5),
                           labels=c("G0/G1", "S", "G2M","G0/G1"))+
        theme_classic()+
        theme(axis.ticks.x = element_blank(), axis.text=element_text(color="black",size=12),axis.title = element_text(color="black",size=14),strip.background = element_blank(),strip.text.x = element_text(size=12,color="black",face = "italic"),legend.position = "top",axis.text.x = element_text(angle = 45,vjust = 0.9,hjust=0.9))+
        facet_wrap(~Var1,scale="free",ncol = 3)
dev.off()  
}

##### EXAMPLE PSEUDOTIME PLOTS WITH DOTS #######
library(reshape2)
genes=c("Myb","Foxj1","Deup1")
DefaultAssay(only_mccs) <- "RNA"

dat=FetchData(only_mccs, genes)
dat$pseudotime <- only_mccs$pseudotime
dat$clus <- only_mccs$integrated_snn_res.0.2

pdf(paste0("v3/mccs_clean_subset/mccs_clean_Deup1_vs_pseudotime_dots.pdf"),height=4,width=8,useDingbats = F)
ggplot(dat %>% filter(!is.na(pseudotime)), aes(x=pseudotime,y=Deup1))+
        geom_point(aes(color=clus))+
        geom_smooth(color="black")+
        scale_color_manual(values=c("#009245",mcc_color(6)[c(6,2,4)],"black"))+
        theme_classic()+
        theme(legend.position = "none")
 dev.off()      


################ E2f7 EXPRESSION #####################
library(cowplot)
library(ggpubr)
library(grid)
library(gridExtra)

DefaultAssay(seur) <- "RNA"
DefaultAssay(only_mccs) <- "RNA"
DefaultAssay(cycling_basal) <- "RNA"

pdf("v3/mcc_timecourse_E2f7_expression.pdf",height=8,width=11,useDingbats = F)
FeaturePlot(seur, "E2f7",pt.size=1,order=T) +  scale_x_reverse() + scale_y_reverse() + theme_void() + scale_color_viridis() + theme(title = element_blank(),legend.position = "none")
dev.off()

s=FeaturePlot(seur, "E2f7",pt.size=1.5,order=T, max.cutoff = "q99") +  scale_x_reverse() + scale_y_reverse() + theme_void() + scale_color_viridis() + theme(title = element_blank())

s_leg=get_legend(s)

pdf("v3/mcc_timecourse_E2f7_legendexpression.pdf",height=4,width=3,useDingbats = F)
grid.newpage()
grid.draw(s_leg)
dev.off()

pdf("v3/mccs_clean_subset/mccs_clean_E2f7_expression.pdf",height=8,width=11,useDingbats = F)
FeaturePlot(only_mccs, "E2f7",pt.size=2.5,order=T, max.cutoff = "q99") +  scale_x_reverse() + theme_void() + scale_color_viridis() + theme(title = element_blank(),legend.position = "none")
dev.off()

m=FeaturePlot(only_mccs, "E2f7",pt.size=2,order=T, max.cutoff = "q99") +  scale_x_reverse() + theme_void() + scale_color_viridis() + theme(title = element_blank())

m_leg=get_legend(m)

pdf("v3/mccs_clean_subset/mccs_clean_E2f7_legendexpression.pdf",height=4,width=3,useDingbats = F)
grid.newpage()
grid.draw(m_leg)
dev.off()


pdf("v3/cycling_basal_subset/cycling_basal_E2f7_expression.pdf",height=8,width=11,useDingbats = F)
FeaturePlot(cycling_basal, "E2f7",pt.size=2.5,order=T, max.cutoff = "q99") +  scale_y_reverse() + theme_void() + scale_color_viridis() + theme(title = element_blank(),legend.position = "none")
dev.off()

c=FeaturePlot(cycling_basal, "E2f7",pt.size=2,order=T, max.cutoff = "q99") +  scale_y_reverse() + theme_void() + scale_color_viridis() + theme(title = element_blank())

c_leg=get_legend(c)

pdf("v3/cycling_basal_subset/cycling_basal_E2f7_legendexpression.pdf",height=4,width=3,useDingbats = F)
grid.newpage()
grid.draw(c_leg)
dev.off()

################### E2f8 EXPRESSION #############################
library(viridis)
library(ggplot2)
library(cowplot)
library(grid)
DefaultAssay(only_mccs) <- "RNA"

pdf("mccs_clean_subset/mccs_clean_E2f8_expression.pdf",height=8,width=11,useDingbats = F)
FeaturePlot(only_mccs, "E2f8",pt.size=2.5,order=T, max.cutoff = "q99") +  scale_x_reverse() + theme_void() + scale_color_viridis() + theme(title = element_blank(),legend.position = "none")
dev.off()

m=FeaturePlot(only_mccs, "E2f8",pt.size=2,order=T, max.cutoff = "q99") +  scale_x_reverse() + theme_void() + scale_color_viridis() + theme(title = element_blank())

m_leg=get_legend(m)

pdf("mccs_clean_subset/mccs_clean_E2f8_legendexpression.pdf",height=4,width=3,useDingbats = F)
grid.newpage()
grid.draw(m_leg)
dev.off()

## cycling basal cells
DefaultAssay(cycling_basal) <- "RNA"

pdf("cycling_basal_subset/cycling_basal_E2f8_expression.pdf",height=8,width=11,useDingbats = F)
FeaturePlot(cycling_basal, "E2f8",pt.size=2.5,order=T, max.cutoff = "q99") +  scale_y_reverse() + theme_void() + scale_color_viridis() + theme(title = element_blank(),legend.position = "none")
dev.off()

m=FeaturePlot(cycling_basal, "E2f8",pt.size=2,order=T, max.cutoff = "q99") +  scale_y_reverse() + theme_void() + scale_color_viridis() + theme(title = element_blank())

m_leg=get_legend(m)

pdf("cycling_basal_subset/cycling_basal_E2f8_legendexpression.pdf",height=4,width=3,useDingbats = F)
grid.newpage()
grid.draw(m_leg)
dev.off()

###################### S and G2M SCORES ##########################
library(UCell)

g2m=read.csv("~/Documents/Reiter_Seq/g2m_phase_human_mgi_genes.csv")
s=read.csv("~/Documents/Reiter_Seq/s_phase_human_mgi_genes.csv")

g2mgenes=g2m$MGI.symbol
sgenes=s$MGI.symbol

seur=AddModuleScore_UCell(seur,features=list(sgenes,g2mgenes),assay="RNA")
Idents(seur) <- "tricycle_celltype"
seur$tricycle_celltype <- factor(seur$tricycle_celltype,levels=c("cyc_G1/G0","mcc_G1/G0","cyc_S","mcc_S","cyc_G2M","mcc_G2M",NA))

a=VlnPlot(subset(seur,idents=c("cyc_G1/G0","mcc_G1/G0","cyc_S","mcc_S")), "signature_1_UCell",group.by="tricycle_celltype",pt.size = 0, cols = c(colors[2],mcc_color(5)[3],colors[2],mcc_color(5)[3])) + theme(legend.position = "none",axis.text=element_text(size=12,color="black"),axis.title = element_text(size=14))+ggtitle("")+ylab("S phase score")+xlab("")

b=VlnPlot(subset(seur,idents=c("cyc_G1/G0","mcc_G1/G0","cyc_G2M","mcc_G2M")), "signature_2_UCell",group.by="tricycle_celltype",pt.size = 0, cols = c(colors[2],mcc_color(5)[3],colors[2],mcc_color(5)[3])) + theme(legend.position = "none",axis.text = element_text(size=12,color="black"),axis.title = element_text(size=14))+ggtitle("")+ylab("G2M phase score")+xlab("")

pdf("v3/mccs_clean_subset/mccs_clean_S_G2M_UCell_score.pdf",height=5,width=4,useDingbats = F)
grid.arrange(a,b)
dev.off()

meta_scores=seur@meta.data[,c("signature_1_UCell","signature_2_UCell","tricycle_celltype","orig.ident")]

meta_score_sum = meta_scores %>% group_by(orig.ident,tricycle_celltype) %>%
        summarise(mean_signature_1_UCell =mean(signature_1_UCell))

write.csv(meta_score_sum, "v3/S_scores_basal_multiciliated_tricycleGrouped.csv")

g2m_sum = meta_scores %>% group_by(orig.ident,tricycle_celltype) %>%
        summarise(mean_signature_2_UCell =mean(signature_2_UCell))

write.csv(g2m_sum, "v3/G2M_scores_basal_multiciliated_tricycleGrouped.csv")

meta_scores_melt=reshape2::melt(meta_scores)

s_score=meta_scores_melt %>% filter(variable == "signature_1_UCell")
g2m_score=meta_scores_melt %>% filter(variable == "signature_2_UCell")
s_score$tricycle_celltype <- factor(s_score$tricycle_celltype,levels=c("cyc_G1/G0","mcc_G1/G0","cyc_S","mcc_S","cyc_G2M","mcc_G2M",NA))
g2m_score$tricycle_celltype <- factor(s_score$tricycle_celltype,levels=c("cyc_G1/G0","mcc_G1/G0","cyc_S","mcc_S","cyc_G2M","mcc_G2M",NA))


pdf("v3/mccs_clean_subset/mccs_clean_S_G2M_UCell_score.pdf",height=3,width=6,useDingbats = F)
grid.arrange(g1, g2, nrow=2)
dev.off()

ms=ggplot(seur@meta.data %>% filter(!is.na(seur$pseudo_mcc)),aes(x=pseudo_mcc,y=signature_1_UCell))+
        geom_smooth()+
        theme_classic()+
        ylab("S Score")+
        xlab("Multiciliated cell pseudotime")+
        theme(axis.text = element_text(size=14),axis.title=element_text(size=12))

m2=ggplot(seur@meta.data %>% filter(!is.na(seur$pseudo_mcc)),aes(x=pseudo_mcc,y=signature_2_UCell))+
        geom_smooth()+
        theme_classic()+
        ylab("G2/M Score")+
        xlab("Multiciliated cell pseudotime")+
        theme(axis.text = element_text(size=14),axis.title=element_text(size=12))

pdf("v3/multiciliated_cell_S_vs_pseudotime.pdf",height=6,width=8,useDingbats = F)
ggarrange(ms,m2,ncol=1)
dev.off()

bs=ggplot(seur@meta.data %>% filter(!is.na(seur$pseudo_cycling)),aes(x=pseudo_cycling,y=signature_1_UCell))+
        geom_smooth()+
        theme_classic()+
        ylab("S Score")+
        xlab("Mitotic cell pseudotime")+
        theme(axis.text = element_text(size=14),axis.title=element_text(size=12))


b2=ggplot(seur@meta.data %>% filter(!is.na(seur$pseudo_cycling)),aes(x=pseudo_cycling,y=signature_2_UCell))+
        geom_smooth()+
        theme_classic()+
        ylab("G2/M Score")+
        xlab("Mitotic cell pseudotime")+
        theme(axis.text = element_text(size=14),axis.title=element_text(size=12))

pdf("v3/muitotic_cell_S_vs_pseudotime.pdf",height=6,width=8,useDingbats = F)
ggarrange(bs,b2,ncol=1)
dev.off()

##### line plots across pseuodtime for regulators

regs=c("Cdk1","Ccna1","Ccna2","Ccne1","Ccne2","Ccnb1","Ccnb2","Ccnd1","Ccnd2","Cdk4","Cdk6","Cdk2","Plk4")

mccs_regs = AverageExpression(only_mccs, assays="RNA",features = regs,group.by="tricycleBinned")
dat=mccs_regs$RNA

dat_melt=reshape2::melt(dat)

for(x in regs){
        pdf(paste0("v3/mccs_clean_subset/mccs_clean_",x,"_vs_tricycleBin.pdf"),height=3,width=5,useDingbats=F)
        print(ggplot(dat_melt %>% filter(Var1 == x),aes(x=Var2,y=value))+
                      geom_point()+
                      geom_line()+
                      xlab("Tricycle Bin")+
                      ylab("Expression")+
                      theme_classic()+
                      ggtitle(x)+
                      geom_vline(xintercept=6,linetype="dashed")+
                      geom_vline(xintercept = 11,linetype="dashed")+
                      geom_vline(xintercept=17,linetype="dashed")+
                      scale_x_continuous(breaks=c(3,8.5,14.5,19.5),
                                         labels=c("G0/G1", "S", "G2M","G0/G1"))+       
                      theme(axis.text = element_text(size=12,color="black"),axis.title = element_text(size=14)))
        dev.off()
}

cyc_regs = AverageExpression(cycling_basal, assays="RNA",features = regs,group.by="tricycleBin")
dat_cyc=cyc_regs$RNA

dat_cyc_melt=reshape2::melt(dat_cyc)

for(x in regs){
        pdf(paste0("v3/cycling_basal_subset/cycling_basal_",x,"_vs_tricycleBin.pdf"),height=4,width=6,useDingbats=F)
        print(ggplot(dat_cyc_melt %>% filter(Var1 == x),aes(x=Var2,y=value))+
                      geom_point()+
                      geom_line()+
                      xlab("Tricycle Bin")+
                      ylab("Expression")+
                      theme_classic()+
                      ggtitle(x)+
                      geom_vline(xintercept=6,linetype="dashed")+
                      geom_vline(xintercept = 11,linetype="dashed")+
                      geom_vline(xintercept=17,linetype="dashed")+
                      scale_x_continuous(breaks=c(3,8.5,14.5,19.5),
                                         labels=c("G0/G1", "S", "G2M","G0/G1"))+
                      theme(axis.text = element_text(size=12,color="black"),axis.title = element_text(size=14)))
        dev.off()
}

################## HEATMAPS for ciliogenesis and cell cycle regulators ########################
library(stringr)
library(dplyr)
library(pheatmap)
library(scales)
library(RColorBrewer)
#genes=read.csv("~/Box Sync/E2f7_paper/multiciation_cycle_genes.csv")
genes=read.csv("~/Box Sync/E2f7_paper/Heatmap_Genelist_regulators.txt")
genes=read.csv("~/Box Sync/E2f7_paper/Heatmap_Genelist.txt")
genes=read.csv("mccs_clean_subset/heatmap_genelist3.csv",header=F)

#genes$Genes.for.heatmap <- str_to_title(genes$Genes.for.heatmap)
genes$Genes.for.heatmap <- str_to_title(genes$V1)

premat=AverageExpression(sub, group.by = "pseudo_group",features =genes$Gene,assay="RNA")

dat_melt=reshape2::melt(premat)

##thresh genes
threshed_genes=NULL
thresh=0.5
for(x in unique(dat_melt$Var1)){
        dat_x=dat_melt %>% filter(Var1 == x)
        bs_dat=dat_x[grep("Cycling*",dat_x$Var2),]
        bs_sum= sum( bs_dat$value > thresh)
        mc_dat=dat_x[grep("MCC*",dat_x$Var2),]
        mc_sum= sum( mc_dat$value > thresh)
        if(bs_sum | mc_sum > 1){
                threshed_genes <- c( threshed_genes,x)
        }
}

mat=AverageExpression(sub, group.by = "pseudo_group",features =threshed_genes,assay="RNA")
col_order = c(paste("MCCs",c(1:20),sep=""))
mat_order=mat$RNA[,match(col_order,colnames(mat$RNA))]

thresh_gene_info=genes[match(threshed_genes,genes$Gene),]

row_anno = as.data.frame(rownames(mat_order))
rownames(row_anno)<-row_anno$`rownames(mat_order)`
#row_anno$Function <- ""
#row_anno$Function[match(thresh_gene_info$Gene,rownames(row_anno))] <- thresh_gene_info$Function
#row_anno$Function <-as.factor(row_anno$Function)

cc_scores=sub@meta.data %>% 
        filter(group == "MCCs") %>%
        group_by(pseudo_group) %>%
        summarise_at(vars(c(UCell_S,UCell_G2M)),              
                     list(mean = mean)) 

cc_scores=cc_scores[match(col_order,cc_scores$pseudo_group),]
cc_scores$s_minmax =rescale(cc_scores$UCell_S_mean)
cc_scores$g2m_minmax =rescale(cc_scores$UCell_G2M_mean)
cc_scores=as.data.frame(cc_scores)
rownames(cc_scores) <- cc_scores$pseudo_group

cc_scores$Pseudo_bin <- c(1:20)

col_anno=cc_scores[,c("Pseudo_bin","s_minmax","g2m_minmax")]
colnames(col_anno) <- c("Pseudotime Bin", "S score", "G2M score")

### annotation - colors
vir_col=viridis_pal(option = "C",direction = -1)

colors_anno=vir_col(20)
names(colors_anno) <- unique(col_anno$`Pseudotime Bin`)
colors_anno = list(`Pseudotime Bin`=colors_anno)

color_fnc=colorRampPalette(c("#CCFFFF","#330066"))
color_fnc2=colorRampPalette(c("#CCFFFF","#006600"))
col_scores=color_fnc(20)

colors_anno[["S score"]]<-col_scores
colors_anno[["G2M score"]]<-color_fnc2(20)

row_colors=RColorBrewer::brewer.pal(8,"Set2")
names(row_colors) <- unique(row_anno$Function)
colors_anno[["Function"]]<-row_colors

data_colors =c("#666666","#6666CC")
names(data_colors) <-c("E2f7 WT","E2f7 Hom")

colors_anno[["Dataset"]] <- data_colors

#p=pheatmap(mat_order[,grep("MCC*",colnames(mat_order))],scale="row",cluster_cols = F,annotation_row = row_anno[,c("Function","cluster"),drop=F],cutree_rows = 8,annotation_col = col_anno,annotation_colors = colors_anno)

p=pheatmap(mat_order[,grep("MCC*",colnames(mat_order))],scale="row",cluster_cols = F,drop=F,cutree_rows = 7,annotation_col = col_anno,annotation_colors = colors_anno)

gene_order=cutree(p$tree_row,k=7)
row_anno$cluster <-NA
row_anno$cluster[match(names(gene_order),row_anno$`rownames(mat_order)`)]<-gene_order

colors_anno[["cluster"]]<- brewer.pal(7, "Set3")

pdf("~/Box Sync/E2f7_paper/mcc_timecourse_onlymccs_cellcycle_genes3_clus7_heatmap.pdf",height=10,width=12,useDingbats = F)
p=pheatmap(mat_order[,grep("MCC*",colnames(mat_order))],scale="row",cluster_cols = F,drop=F,cutree_rows = 7,annotation_col = col_anno,annotation_row = row_anno[,"cluster",drop=F],annotation_colors = colors_anno,show_colnames = F)
dev.off()


# for first genes list
new_order=c(gene_order[gene_order ==5],gene_order[gene_order==1],gene_order[gene_order == 2],gene_order[gene_order==3],gene_order[gene_order==7],gene_order[gene_order==8],gene_order[gene_order==6],gene_order[gene_order==4])

new_order=c(gene_order[gene_order ==8],gene_order[gene_order==1],gene_order[gene_order == 2],gene_order[gene_order==3],gene_order[gene_order==5],gene_order[gene_order==6],gene_order[gene_order==4],gene_order[gene_order==7])

#pdf("~/Box Sync/E2f7_paper/mcc_timecourse_onlymccs_cellcycle_TF_heatmap.pdf",height=20,width=12,useDingbats = F)
#p=pheatmap(mat_order[match(names(new_order),rownames(mat_order)),grep("MCC*",colnames(mat_order))],scale="row",cluster_cols = F,cluster_rows = F,annotation_row = row_anno[,c("Function"),drop=F],cutree_rows = 8,annotation_col = col_anno,annotation_colors = colors_anno,show_colnames = F,gaps_row = c(10,10+15,25+8,25+8+6,25+8+6+34,25+8+6+34+24,25+8+6+34+24+6,25+8+6+34+24+6+7))
#dev.off()

colors_anno[["cluster"]]<- brewer.pal(8, "Set3")

pdf("~/Box Sync/E2f7_paper/mcc_timecourse_onlymccs_cellcycle_regulators_heatmap.pdf",height=10,width=12,useDingbats = F)
p=pheatmap(mat_order[match(names(new_order),rownames(mat_order)),grep("MCC*",colnames(mat_order))],scale="row",cluster_cols = F,cluster_rows = F,cutree_rows = 8,annotation_row = row_anno[,"cluster",drop=F],annotation_col = col_anno,annotation_colors = colors_anno,show_colnames = F)
dev.off()

pdf("~/Box Sync/E2f7_paper/mcc_timecourse_onlymccs_cellcycle_regulators_heatmap_hierarchial.pdf",height=10,width=12,useDingbats = F)
p=pheatmap(mat_order[,grep("MCC*",colnames(mat_order))],scale="row",cluster_cols = F,cluster_rows = T,annotation_row = row_anno[,"cluster",drop=F],cutree_rows = 8,annotation_col = col_anno,annotation_colors = colors_anno,show_colnames = F)
dev.off()

pdf("~/Box Sync/E2f7_paper/mcc_timecourse_onlymccs_cellcycle_long_heatmap.pdf",height=10,width=12,useDingbats = F)
p=pheatmap(mat_order[match(names(new_order),rownames(mat_order)),grep("MCC*",colnames(mat_order))],scale="row",cluster_cols = F,cluster_rows = F,cutree_rows = 8,annotation_row = row_anno[,"cluster",drop=F],annotation_col = col_anno,annotation_colors = colors_anno,show_colnames = F)
dev.off()

pdf("~/Box Sync/E2f7_paper/mcc_timecourse_onlymccs_cellcycle_long_heatmap_hierarchial.pdf",height=10,width=12,useDingbats = F)
p=pheatmap(mat_order[,grep("MCC*",colnames(mat_order))],scale="row",cluster_cols = F,cluster_rows = T,cutree_rows = 8,annotation_row = row_anno[,"cluster",drop=F],annotation_col = col_anno,annotation_colors = colors_anno,show_colnames = F)
dev.off()

######### print counts and metadata for GEO ##########

DimPlot(seur, label=T,group.by="integrated_snn_res.0.3")
meta=seur@meta.data
meta$cluster_names =meta$integrated_snn_res.0.3

meta=meta %>% mutate(cluster_names=recode(cluster_names,
                                          `1`="Basal stem",
                                          `2`="Basal to intermediate",
                                          `3`="Secretory",
                                          `4`="Multiciliated 3",
                                          `5`="S",
                                          `6`="G2M",
                                          `7`="Tnfrsf12a+",
                                          `8`="Multiciliated 1",
                                          `9`="Multiciliated 2",
                                          `0`="Intermediate"
))

FeaturePlot(only_mccs, "pseudotime")

seur@meta.data=meta

DimPlot(seur, group.by="cluster_names")

Idents(seur) <- "cluster_names"
marks=FindAllMarkers(seur, assay="RNA",only.pos = T)
write.csv(marks, "~/Box Sync/E2f7_paper/Supplementary_Table1.csv",row.names = F)
## add pseudotime values and clusters
seur$multiciliated_pseudotime <- NA
seur$multiciliated_pseudotime[match(rownames(only_mccs@meta.data),rownames(seur@meta.data))]<-only_mccs$pseudotime

seur$basal_pseudotime <-NA
seur$basal_pseudotime[match(rownames(cycling_basal@meta.data),rownames(seur@meta.data))]<-cycling_basal$pseudo_cycling

FeaturePlot(seur, "multiciliated_pseudotime")
FeaturePlot(seur, "basal_pseudotime")

DimPlot(only_mccs,group.by="integrated_snn_res.0.2",label=T)

seur$multiciliated_clusters <- NA
seur$multiciliated_clusters[match(rownames(only_mccs@meta.data),rownames(seur@meta.data))]<- as.character(only_mccs$integrated_snn_res.0.2)
seur$multiciliated_cluster_names <- seur$multiciliated_clusters
seur@meta.data=seur@meta.data %>% mutate(multiciliated_cluster_names=recode(multiciliated_cluster_names,
                                                                            `0`="Intermediate",
                                                                            `1`="Multiciliated 3",
                                                                            `2`="Multciliated 1",
                                                                            `3`="Multciliated 2"))

DimPlot(seur, group.by="multiciliated_cluster_names")

### add UMAPs

full_umap =Embeddings(seur, "umap")
mcc_umap=Embeddings(only_mccs,"umap")
basal_umap=Embeddings(cycling_basal,"umap")

seur$UMAP_1<-full_umap[,c("UMAP_1")]
seur$UMAP_2<-full_umap[,c("UMAP_2")]

seur$multiciliated_UMAP_1 <-NA
seur$multiciliated_UMAP_1[match(rownames(mcc_umap),rownames(seur@meta.data))] <- mcc_umap[,c("UMAP_1")]
seur$multiciliated_UMAP_2 <-NA
seur$multiciliated_UMAP_2[match(rownames(mcc_umap),rownames(seur@meta.data))] <-mcc_umap[,c("UMAP_2")]

seur$basal_UMAP_1<-NA
seur$basal_UMAP_1[match(rownames(basal_umap),rownames(seur@meta.data))] <- basal_umap[,c("UMAP_1")]
seur$basal_UMAP_2<-NA
seur$basal_UMAP_2[match(rownames(basal_umap),rownames(seur@meta.data))] <- basal_umap[,c("UMAP_2")]


ggplot(seur@meta.data,aes(x=basal_UMAP_1,y=basal_UMAP_2,color=integrated_snn_res.0.3))+
        geom_point()

seur$S_score <- seur$signature_1_UCell
seur$G2M_score<-seur$signature_2_UCell

seur$subset_group = NA
seur$subset_group[match(rownames(only_mccs@meta.data),rownames(seur@meta.data))]<-"Multiciliated"
seur$subset_group[match(rownames(cycling_basal@meta.data),rownames(seur@meta.data))]<-"Basal stem cells"

columns_to_keep=c("orig.ident","nCount_RNA","nFeature_RNA","percent.mt","UMAP_1","UMAP_2","integrated_snn_res.0.3","cluster_names","tricyclePosition","S_score","G2M_score","subset_group","multiciliated_clusters","multiciliated_cluster_names","multiciliated_UMAP_1","multiciliated_UMAP_2","multiciliated_pseudotime","basal_pseudotime","basal_UMAP_1","basal_UMAP_2")

for_printing=seur@meta.data[,columns_to_keep]

write.csv(for_printing, file="GEO_files/mcc_timecourse_metadata.csv")
library(Matrix)

writeMM(seur[["RNA"]]@counts, file="GEO_files/mcc_timecourse_counts.mtx")


###
DefaultAssay(only_mccs) <- "RNA"
dir.create("v3/mccs_clean_subset/gene_vs_pseudotime")
cilia_genes=read.csv("~/Documents/Reiter_Seq/CuratedCiliaAndBasalBodyGenes_18.csv")
ccgenes=read.csv(file="v3/cellcycle_genes_for_DE.csv")

#for(x in cilia_genes$Gene.name..Mus.musculus.[cilia_genes$Gene.name..Mus.musculus. %in% rownames(only_mccs[["RNA"]]@data)]){

for(x in ccgenes$x[ccgenes$x %in% rownames(only_mccs[["RNA"]]@data)]){    
        dat=FetchData(only_mccs, vars=x)
        colnames(dat)<-"Gene"
        dat$pseudotime =only_mccs$pseudotime
        pdf(paste0("v3/mccs_clean_subset/gene_vs_pseudotime/mccs_clean_",x,"_vs_pseudotime.pdf"),height=4,width=6,useDingbats = F)
        print(ggplot(dat %>% filter(!is.na(dat$pseudotime)), aes(x=pseudotime,y=Gene))+
                      geom_smooth()+
                      theme_classic()+
                      xlab("Pseudotime"))
        dev.off()
}

####### Gene groups over pseudotime ###
library(scales)
selectgenes=c("Ccnd1","Cdk4","Cdk6")

   
dat=FetchData(only_mccs, vars=selectgenes)
dat$pseudotime =only_mccs$pseudotime
dat$clusters=only_mccs$integrated_snn_res.0.2
dat_melt=reshape2::melt(dat,id.vars = c("pseudotime","clusters"))


p1=ggplot(dat_melt %>% filter(!is.na(dat_melt$pseudotime)), aes(x=pseudotime,y=value,color=variable))+
        geom_smooth()+
        theme_classic()+
        xlab("Pseudotime")+
        geom_jitter(aes(x=pseudotime,y=1.2,color=clusters),height=0.05)+
        scale_color_manual(values=c(only_mccs_col,c("red","blue","green")))

pdf("v3/mccs_clean_subset/mcc_timecourse_mccs_clean_Ccnd1_Cdk4_Cdk6_withclusterid.pdf",height=4,width=5,useDingbats = F)
p1
dev.off()

p1dat=ggplot_build(p1)   

linedat=p1dat$data[[1]]
ccnd1dat=linedat %>% filter(colour == "red")
ccnd1dat$y_rescale=rescale(ccnd1dat$y)
cdk4dat=linedat %>% filter(colour == "blue")
cdk4dat$y_rescale = rescale(cdk4dat$y)
cdk6dat=linedat %>% filter(colour == "green")
cdk6dat$y_rescale = rescale(cdk6dat$y)

newdat=rbind(ccnd1dat,cdk4dat)
newdat=rbind(newdat,cdk6dat)

newdat$gene = "Ccnd1"
newdat$gene[newdat$colour == "blue"] <- "Cdk4"
newdat$gene[newdat$colour == "green"] <- "Cdk6"

pdf("v3/mccs_clean_subset/mcc_timecourse_mccs_clean_Ccnd1_Cdk4_Cdk6_norm_vs_pseudotime.pdf",height=4,width=5,useDingbats = F)
ggplot(newdat, aes(x=x,y=y_rescale,color=gene))+
        geom_line(linewidth=1)+
        theme_classic()+
        ylab("Normalized Gene Expression")+
        xlab("Pseudotime")
dev.off()

#selectgenes=c("Ccnd1","Cdk4","Cdk6")
selectgenes=c("Cdk4","Cdk2","Cdk1","Cdk5")
   
dat_full=FetchData(only_mccs, vars=selectgenes)
dat_full$pseudotime =only_mccs$pseudotime
dat_full$clusters=only_mccs$integrated_snn_res.0.2

dat_rescale=dat_full %>% filter(!is.na(dat_full$pseudotime))

dat=as.data.frame(dat_rescale)
dat_for_scaling=dat[,!colnames(dat) %in% "clusters"]

for(x in 1:length(colnames(dat_for_scaling))){
       dat_for_scaling[,x] <- rescale(dat_for_scaling[,x]) 
}


dat_for_scaling$pseudotime <- dat_rescale$pseudotime
dat_for_scaling$clusters <- dat_rescale$clusters

dat_melt=reshape2::melt(dat_for_scaling,id.vars = c("pseudotime","clusters"))
        
        #pdf(paste0("v3/mccs_clean_subset/mccs_clean_Ccnd1_Cdk4_Cdk6_vs_pseudotime.pdf"),height=5,width=6,useDingbats = F)
        
pdf(paste0("v3/mccs_clean_subset/mccs_clean_Cdks_vs_pseudotime.pdf"),height=5,width=6,useDingbats = F)

ggplot(dat_melt, aes(x=pseudotime,y=value,color=variable))+
        geom_smooth()+
        theme_classic()+
        xlab("Pseudotime")+
        geom_jitter(aes(x=pseudotime,y=max(value)+0.5,color=clusters),height=0.05)+
        scale_color_manual(values=c(only_mccs_col,c("red","blue","green","grey17")))
dev.off()


